# лёгкий образ Node.js
FROM node:20-alpine

# рабочая директория внутри контейнера
WORKDIR /app

# сначала копируем манифесты
COPY package.json package-lock.json ./

# ставим только prod-зависимости
RUN npm install --only=production

# копируем код сервера
COPY server ./server

# контейнер слушает этот порт
EXPOSE 3001

# команда запуска приложения
CMD ["node", "server/server.js"]
